export const Message = {
    success_registered : 'successfully registered',
    enter_verify : 'Enter your Verification Code Here'
};

export const RegistrationMessage = {
    name: 'user name is required',
    address: 'address is required',
    mobileNo: 'mobile no is required',
    min_mobileNo: 'please enter valid mobile no.',
    max_mobileNo: 'please enter valid mobile no.',
    num_mobileNo: 'please enter valid mobile no.',
    altMobileNO: 'alternative mobile number is required',
    password: 'password is required',
    strong_password: 'a password between 8 to 20 characters which contain at least one lowercase letter, one uppercase letter, one numeric digit, and one special character.',
    photo: 'profile picture is required',
    married: '',
    specialist: '',
    description: '',
    salary: 'salary is required',
    num_salary: 'please enter valid salary',
    age: '',
    study: '',
    emailId: 'email id is required',
    availibility: '',
    role: 'role is required',
    workExperience: '',
    userId: '',
    houseNo: 'House No is required',
    address1: '',
    landmark: '',
    city: 'city is required',
    state: 'state is required',
    country: 'country is required',
    pincode:'',
    centerName: 'center name is required',
    periodOfWork: 'period of work is required',
    comment: '',
    PMName: 'project manager name is required',
    PMMobile: 'project manager mobile number is required',
    KIName:'kitchen incharge name is required',
    KIMobile: 'kitchen incharge mobile no is required',
    KIEmailId:'kitchen incharge email id is required',
    WISalary: 'enter the salary',
    status: '',
}
